TASK_MODELS = {
    "Classify":  ["PPLCNet", "YOLO-Cls", "EfficientNet"],
    "Detect":    ["YOLO-Det", "RFDETR-Det"],
    "Segment":   ["YOLO-Seg", "DinoUperNet", "DinoV3ConvNextUperNet", "DinoV3ConvNextMask2Former", "HRNet", "RFDETR-Seg"],
    "Anomaly":   ["DinomalyV2"],
    "Recognize": ["PPOCRv5ServerRec", "PPOCRv5MobileRec"],
}

# model_module / model_class must match actual class names in memolib
MODEL_INFO = {
    "PPLCNet": {
        "config_module":    "MemoLib.Model.PPLCNet.PPLCNetConfig",
        "config_class":     "TrainingConfig",
        "model_module":     "MemoLib.Model.PPLCNet.PPLCNetModel",
        "model_class":      "PPLCNet",
        "arch_enum_module": "MemoLib.Model.BaseModel.eClassificationModel",
        "arch_enum_class":  "ePPLCNetModel",
        "fixed_fields":     {},
    },
    "YOLO-Cls": {
        "config_module":    "MemoLib.Model.YOLO.YoloConfig",
        "config_class":     "TrainingConfig",
        "model_module":     "MemoLib.Model.YOLO.YoloModel",
        "model_class":      "Yolo",
        "arch_enum_module": "MemoLib.Model.BaseModel.eClassificationModel",
        "arch_enum_class":  "eYoloClassificationModel",
        "fixed_fields":     {"TaskType": "classify"},
        "default_arch":     "Yolo11n",
    },
    "EfficientNet": {
        "config_module":    "MemoLib.Model.Efficientnet.EfficientNetConfig",
        "config_class":     "TrainingConfig",
        "model_module":     "MemoLib.Model.Efficientnet.EfficientNetModel",
        "model_class":      "EfficientNet",
        "arch_enum_module": "MemoLib.Model.BaseModel.eClassificationModel",
        "arch_enum_class":  "eEfficientNetModel",
        "fixed_fields":     {},
    },
    "YOLO-Det": {
        "config_module":    "MemoLib.Model.YOLO.YoloConfig",
        "config_class":     "TrainingConfig",
        "model_module":     "MemoLib.Model.YOLO.YoloModel",
        "model_class":      "Yolo",
        "arch_enum_module": "MemoLib.Model.BaseModel.eDetectionModel",
        "arch_enum_class":  "eYoloDetectionModel",
        "fixed_fields":     {"TaskType": "detect"},
        "default_arch":     "Yolo11n",
    },
    "RFDETR-Det": {
        "config_module":    "MemoLib.Model.RFDETR.RFDETRConfig",
        "config_class":     "TrainingConfig",
        "model_module":     "MemoLib.Model.RFDETR.RFDETRModel",
        "model_class":      "RFDETRModel",
        "arch_enum_module": "MemoLib.Model.BaseModel.eDetectionModel",
        "arch_enum_class":  "eRFDetrDetectionModel",
        "fixed_fields":     {"TaskType": "detect"},
    },
    "YOLO-Seg": {
        "config_module":    "MemoLib.Model.YOLO.YoloConfig",
        "config_class":     "TrainingConfig",
        "model_module":     "MemoLib.Model.YOLO.YoloModel",
        "model_class":      "Yolo",
        "arch_enum_module": "MemoLib.Model.BaseModel.eSegmentationModel",
        "arch_enum_class":  "eYoloSegmentationModel",
        "fixed_fields":     {"TaskType": "segment"},
        "default_arch":     "Yolo11n",
    },
    "DinoUperNet": {
        "config_module":    "MemoLib.Model.DinoUperNet.DinoUperNetConfig",
        "config_class":     "TrainingConfig",
        "model_module":     "MemoLib.Model.DinoUperNet.DinoUperNet",
        "model_class":      "DinoUperNet",
        "arch_enum_module": "MemoLib.Model.BaseModel.eSegmentationModel",
        "arch_enum_class":  "eDinoUperNetModel",
        "fixed_fields":     {},
    },
    "DinoV3ConvNextUperNet": {
        "config_module":    "MemoLib.Model.DinoV3ConvNextUperNet.DinoV3ConvNextUperNetConfig",
        "config_class":     "TrainingConfig",
        "model_module":     "MemoLib.Model.DinoV3ConvNextUperNet.DinoV3ConvNextUperNet",
        "model_class":      "DinoV3ConvNextUperNet",
        "arch_enum_module": "MemoLib.Model.BaseModel.eSegmentationModel",
        "arch_enum_class":  "eDinoV3ConvNextUperNetModel",
        "fixed_fields":     {},
    },
    "HRNet": {
        "config_module":    "MemoLib.Model.HRNet.HRNetConfig",
        "config_class":     "TrainingConfig",
        "model_module":     "MemoLib.Model.HRNet.HRNet",
        "model_class":      "HRNet",
        "arch_enum_module": "MemoLib.Model.BaseModel.eSegmentationModel",
        "arch_enum_class":  "eHRNetSegmentationModel",
        "fixed_fields":     {},
    },
    "RFDETR-Seg": {
        "config_module":    "MemoLib.Model.RFDETR.RFDETRConfig",
        "config_class":     "TrainingConfig",
        "model_module":     "MemoLib.Model.RFDETR.RFDETRModel",
        "model_class":      "RFDETRModel",
        "arch_enum_module": "MemoLib.Model.BaseModel.eDetectionModel",
        "arch_enum_class":  "eRFDetrDetectionModel",
        "fixed_fields":     {"TaskType": "segment"},
    },
    "DinomalyV2": {
        "config_module":    "MemoLib.Model.Dinomaly.DinomalyConfig",
        "config_class":     "TrainingConfig",
        "model_module":     "MemoLib.Model.Dinomaly.DinomalyModel",
        "model_class":      "DinomalyModel",
        "arch_enum_module": "MemoLib.Model.BaseModel.eAnomalyModel",
        "arch_enum_class":  "eDinomalyModel",
        "fixed_fields":     {},
    },
    "PPOCRv5ServerRec": {
        "config_module":    "MemoLib.Model.PPOCRv5ServerRec.PPOCRv5ServerRecConfig",
        "config_class":     "TrainingConfig",
        "model_module":     "MemoLib.Model.PPOCRv5ServerRec.PPOCRv5ServerRecModel",
        "model_class":      "PPOCRv5ServerRec",
        "arch_enum_module": "MemoLib.Model.BaseModel.eRecognitionModel",
        "arch_enum_class":  "ePPOCRv5ServerRecModel",
        "fixed_fields":     {},
    },
    "PPOCRv5MobileRec": {
        "config_module":    "MemoLib.Model.PPOCRv5MobileRec.PPOCRv5MobileRecConfig",
        "config_class":     "TrainingConfig",
        "model_module":     "MemoLib.Model.PPOCRv5MobileRec.PPOCRv5MobileRecModel",
        "model_class":      "PPOCRv5MobileRec",
        "arch_enum_module": "MemoLib.Model.BaseModel.eRecognitionModel",
        "arch_enum_class":  "ePPOCRv5MobileRecModel",
        "fixed_fields":     {},
    },
}

TRAIN_RESULT_DIR = "TrainResult"
